# Generated by Django 3.1.3 on 2021-03-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210317_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
